services:
  api-gateway:
    image: url-shortener-nginx
    ports:
      - "80:80"
    depends_on:
      - url-shortening-service
      - auth-service
    networks:
      - url-net

  url-shortening-service:
    image: url-shortening-service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=url_shortener
      - DB_USER=url_user
      - DB_PASSWORD=your_secure_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - url-net

  auth-service:
    image: auth-service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=url_shortener
      - DB_USER=url_user
      - DB_PASSWORD=your_secure_password
      - JWT_SECRET=your_jwt_secret_key
      - PORT=3000
      - NODE_ENV=development 
      - DB_SSL=false
      - DB_MAX_CONNECTIONS=20
      - DB_IDLE_TIMEOUT=30000
      - DB_CONNECTION_TIMEOUT=2000
      - DB_CONNECTION_RETRIES=5
      - DB_RETRY_INTERVAL=5000 
      - JWT_REFRESH_SECRET=your_very_secret_refresh_key_change_in_production
      - JWT_ACCESS_EXPIRATION=1h
      - JWT_REFRESH_EXPIRATION=7d
      - JWT_REFRESH_REMEMBER_EXPIRATION=30d 
      - BCRYPT_SALT_ROUNDS=10
      - RATE_LIMIT_MAX=100
      - INVALIDATE_SESSIONS_ON_PASSWORD_CHANGE=false 
      - LOG_LEVEL=info
    depends_on:
      - postgres
    networks:
      - url-net

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=url_user
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_DB=url_shortener
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - url-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - url-net

networks:
  url-net:
    driver: bridge

volumes:
  pgdata: